emb_p1orig<-read.csv(file.choose(),header=TRUE)
emb_p2orig<-read.csv(file.choose(),header=TRUE)

lar_p1orig<-read.csv(file.choose(),header=TRUE)
lar_p2orig<-read.csv(file.choose(),header=TRUE)

lrv_p1orig<-read.csv(file.choose(),header=TRUE)
lrv_p2orig<-read.csv(file.choose(),header=TRUE)


par(mfrow=c(2,4))

#embryo
plot(emb_p1orig$A1~emb_p1orig$Time.Min.)
plot(emb_p1orig$A2~emb_p1orig$Time.Min.)
plot(emb_p1orig$A3~emb_p1orig$Time.Min.)
plot(emb_p1orig$A4~emb_p1orig$Time.Min.)
plot(emb_p1orig$A5~emb_p1orig$Time.Min.)
plot(emb_p1orig$A6~emb_p1orig$Time.Min.)
plot(emb_p1orig$B1~emb_p1orig$Time.Min.)
plot(emb_p1orig$B2~emb_p1orig$Time.Min.)

plot(emb_p1orig$B3~emb_p1orig$Time.Min.)
plot(emb_p1orig$B4~emb_p1orig$Time.Min.)
plot(emb_p1orig$B5~emb_p1orig$Time.Min.)
plot(emb_p1orig$B6~emb_p1orig$Time.Min.)
plot(emb_p1orig$C1~emb_p1orig$Time.Min.)
plot(emb_p1orig$C2~emb_p1orig$Time.Min.)
plot(emb_p1orig$C3~emb_p1orig$Time.Min.)
plot(emb_p1orig$C4~emb_p1orig$Time.Min.)

plot(emb_p1orig$C5~emb_p1orig$Time.Min.)
plot(emb_p1orig$C6~emb_p1orig$Time.Min.)
plot(emb_p1orig$D1~emb_p1orig$Time.Min.)
plot(emb_p1orig$D2~emb_p1orig$Time.Min.)
plot(emb_p1orig$D3~emb_p1orig$Time.Min.)
plot(emb_p1orig$D4~emb_p1orig$Time.Min.)
plot(emb_p1orig$D5~emb_p1orig$Time.Min.)
plot(emb_p1orig$D6~emb_p1orig$Time.Min.)


plot(emb_p2orig$A1~emb_p2orig$Time.Min.)
plot(emb_p2orig$A2~emb_p2orig$Time.Min.)
plot(emb_p2orig$A3~emb_p2orig$Time.Min.)
plot(emb_p2orig$A4~emb_p2orig$Time.Min.)
plot(emb_p2orig$A5~emb_p2orig$Time.Min.)
plot(emb_p2orig$A6~emb_p2orig$Time.Min.)
plot(emb_p2orig$B1~emb_p2orig$Time.Min.)
plot(emb_p2orig$B2~emb_p2orig$Time.Min.)

plot(emb_p2orig$B3~emb_p2orig$Time.Min.)
plot(emb_p2orig$B4~emb_p2orig$Time.Min.)
plot(emb_p2orig$B5~emb_p2orig$Time.Min.)
plot(emb_p2orig$B6~emb_p2orig$Time.Min.)
plot(emb_p2orig$C1~emb_p2orig$Time.Min.)
plot(emb_p2orig$C2~emb_p2orig$Time.Min.)
plot(emb_p2orig$C3~emb_p2orig$Time.Min.)
plot(emb_p2orig$C4~emb_p2orig$Time.Min.)

plot(emb_p2orig$C5~emb_p2orig$Time.Min.)
plot(emb_p2orig$C6~emb_p2orig$Time.Min.)
plot(emb_p2orig$D1~emb_p2orig$Time.Min.)
plot(emb_p2orig$D2~emb_p2orig$Time.Min.)
plot(emb_p2orig$D3~emb_p2orig$Time.Min.)
plot(emb_p2orig$D4~emb_p2orig$Time.Min.)
plot(emb_p2orig$D5~emb_p2orig$Time.Min.)
plot(emb_p2orig$D6~emb_p2orig$Time.Min.)


#2dph
plot(lar_p1orig$A1~lar_p1orig$Time.Min.)
plot(lar_p1orig$A2~lar_p1orig$Time.Min.)
plot(lar_p1orig$A3~lar_p1orig$Time.Min.)
plot(lar_p1orig$A4~lar_p1orig$Time.Min.)
plot(lar_p1orig$A5~lar_p1orig$Time.Min.)
plot(lar_p1orig$A6~lar_p1orig$Time.Min.)
plot(lar_p1orig$B1~lar_p1orig$Time.Min.)
plot(lar_p1orig$B2~lar_p1orig$Time.Min.)

plot(lar_p1orig$B3~lar_p1orig$Time.Min.)
plot(lar_p1orig$B4~lar_p1orig$Time.Min.)
plot(lar_p1orig$B5~lar_p1orig$Time.Min.)
plot(lar_p1orig$B6~lar_p1orig$Time.Min.)
plot(lar_p1orig$C1~lar_p1orig$Time.Min.)
plot(lar_p1orig$C2~lar_p1orig$Time.Min.)
plot(lar_p1orig$C3~lar_p1orig$Time.Min.)
plot(lar_p1orig$C4~lar_p1orig$Time.Min.)

plot(lar_p1orig$C5~lar_p1orig$Time.Min.)
plot(lar_p1orig$C6~lar_p1orig$Time.Min.)
plot(lar_p1orig$D1~lar_p1orig$Time.Min.)
plot(lar_p1orig$D2~lar_p1orig$Time.Min.)
plot(lar_p1orig$D3~lar_p1orig$Time.Min.)
plot(lar_p1orig$D4~lar_p1orig$Time.Min.)
plot(lar_p1orig$D5~lar_p1orig$Time.Min.)
plot(lar_p1orig$D6~lar_p1orig$Time.Min.)


plot(lar_p2orig$A1~lar_p2orig$Time.Min.)
plot(lar_p2orig$A2~lar_p2orig$Time.Min.)
plot(lar_p2orig$A3~lar_p2orig$Time.Min.)
plot(lar_p2orig$A4~lar_p2orig$Time.Min.)
plot(lar_p2orig$A5~lar_p2orig$Time.Min.)
plot(lar_p2orig$A6~lar_p2orig$Time.Min.)
plot(lar_p2orig$B1~lar_p2orig$Time.Min.)
plot(lar_p2orig$B2~lar_p2orig$Time.Min.)

plot(lar_p2orig$B3~lar_p2orig$Time.Min.)
plot(lar_p2orig$B4~lar_p2orig$Time.Min.)
plot(lar_p2orig$B5~lar_p2orig$Time.Min.)
plot(lar_p2orig$B6~lar_p2orig$Time.Min.)
plot(lar_p2orig$C1~lar_p2orig$Time.Min.)
plot(lar_p2orig$C2~lar_p2orig$Time.Min.)
plot(lar_p2orig$C3~lar_p2orig$Time.Min.)
plot(lar_p2orig$C4~lar_p2orig$Time.Min.)

plot(lar_p2orig$C5~lar_p2orig$Time.Min.)
plot(lar_p2orig$C6~lar_p2orig$Time.Min.)
plot(lar_p2orig$D1~lar_p2orig$Time.Min.)
plot(lar_p2orig$D2~lar_p2orig$Time.Min.)
plot(lar_p2orig$D3~lar_p2orig$Time.Min.)
plot(lar_p2orig$D4~lar_p2orig$Time.Min.)
plot(lar_p2orig$D5~lar_p2orig$Time.Min.)
plot(lar_p2orig$D6~lar_p2orig$Time.Min.)



#5dph
plot(lrv_p1orig$A1~lrv_p1orig$Time.Min.)
plot(lrv_p1orig$A2~lrv_p1orig$Time.Min.)
plot(lrv_p1orig$A3~lrv_p1orig$Time.Min.)
plot(lrv_p1orig$A4~lrv_p1orig$Time.Min.)
plot(lrv_p1orig$A5~lrv_p1orig$Time.Min.)
plot(lrv_p1orig$A6~lrv_p1orig$Time.Min.)
plot(lrv_p1orig$B1~lrv_p1orig$Time.Min.)
plot(lrv_p1orig$B2~lrv_p1orig$Time.Min.)

plot(lrv_p1orig$B3~lrv_p1orig$Time.Min.)
plot(lrv_p1orig$B4~lrv_p1orig$Time.Min.)
plot(lrv_p1orig$B5~lrv_p1orig$Time.Min.)
plot(lrv_p1orig$B6~lrv_p1orig$Time.Min.)
plot(lrv_p1orig$C1~lrv_p1orig$Time.Min.)
plot(lrv_p1orig$C2~lrv_p1orig$Time.Min.)
plot(lrv_p1orig$C3~lrv_p1orig$Time.Min.)
plot(lrv_p1orig$C4~lrv_p1orig$Time.Min.)

plot(lrv_p1orig$C5~lrv_p1orig$Time.Min.)
plot(lrv_p1orig$C6~lrv_p1orig$Time.Min.)
plot(lrv_p1orig$D1~lrv_p1orig$Time.Min.)
plot(lrv_p1orig$D2~lrv_p1orig$Time.Min.)
plot(lrv_p1orig$D3~lrv_p1orig$Time.Min.)
plot(lrv_p1orig$D4~lrv_p1orig$Time.Min.)
plot(lrv_p1orig$D5~lrv_p1orig$Time.Min.)
plot(lrv_p1orig$D6~lrv_p1orig$Time.Min.)


plot(lrv_p2orig$A1~lrv_p2orig$Time.Min.)
plot(lrv_p2orig$A2~lrv_p2orig$Time.Min.)
plot(lrv_p2orig$A3~lrv_p2orig$Time.Min.)
plot(lrv_p2orig$A4~lrv_p2orig$Time.Min.)
plot(lrv_p2orig$A5~lrv_p2orig$Time.Min.)
plot(lrv_p2orig$A6~lrv_p2orig$Time.Min.)
plot(lrv_p2orig$B1~lrv_p2orig$Time.Min.)
plot(lrv_p2orig$B2~lrv_p2orig$Time.Min.)

plot(lrv_p2orig$B3~lrv_p2orig$Time.Min.)
plot(lrv_p2orig$B4~lrv_p2orig$Time.Min.)
plot(lrv_p2orig$B5~lrv_p2orig$Time.Min.)
plot(lrv_p2orig$B6~lrv_p2orig$Time.Min.)
plot(lrv_p2orig$C1~lrv_p2orig$Time.Min.)
plot(lrv_p2orig$C2~lrv_p2orig$Time.Min.)
plot(lrv_p2orig$C3~lrv_p2orig$Time.Min.)
plot(lrv_p2orig$C4~lrv_p2orig$Time.Min.)

plot(lrv_p2orig$C5~lrv_p2orig$Time.Min.)
plot(lrv_p2orig$C6~lrv_p2orig$Time.Min.)
plot(lrv_p2orig$D1~lrv_p2orig$Time.Min.)
plot(lrv_p2orig$D2~lrv_p2orig$Time.Min.)
plot(lrv_p2orig$D3~lrv_p2orig$Time.Min.)
plot(lrv_p2orig$D4~lrv_p2orig$Time.Min.)
plot(lrv_p2orig$D5~lrv_p2orig$Time.Min.)
plot(lrv_p2orig$D6~lrv_p2orig$Time.Min.)